config/routes.rb
GameOn::Application.routes.draw do
  resources :recipes

  root 'recipes#index'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :find_recipe, only: [:edit, :show]

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def show
  end

  def index
    @recipes = Recipe.all
  end

  def create
    @recipe = Recipe.new(params.require(:recipe).permit(:title, :description, :instructions))
    if @recipe.save
      redirect_to recipes_path
    else
      render :edit
    end
  end

  private

  def find_recipe
    @recipe = Recipe.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameOn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <fieldset>
  <%= f.label :title %>
  <%= f.text_field :title %>
</fieldset>
<fieldset>
  <%= f.label :description %>
  <%= f.text_field :description %>
</fieldset>
<fieldset>
  <%= f.label :instructions %>
  <%= f.text_field :instructions %>
</fieldset>
<section>
  <%= f.submit %>
  <%= link_to :back %>
</section>
<% end %>

app/views/recipes/_recipe.html.erb
<li>
<%= link_to recipe.title, recipe_path(recipe) %>
</li>

app/views/recipes/edit.html.erb
<%= render partial: 'form' %>

app/views/recipes/index.html.erb
<ul>
  <%= render @recipes %>
</ul>
<%= link_to 'new recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<%= render partial: 'form' %>

app/views/recipes/show.html.erb
<article>
<h1>
<%= @recipe.title %>
</h1>

<p>
<%= @recipe.description %>
</p>


# ingredients


<p>
<%= @recipe.instructions %>
</p>
</article>

<%= link_to 'all recipes', recipes_path %>